name: sklearn-1.5
channels:
- conda-forge
- anaconda
dependencies:
- python=3.10
- pip=24.2
- pandas~=2.2.3
- scipy~=1.14.1
- numpy~=2.1.1
- pip:
  - scikit-learn-intelex==2024.7.0
  - azureml-core==1.57.0.post2
  - azure-ai-ml==1.20.0
  - azureml-defaults==1.57.0.post1
  - azureml-mlflow==1.57.0.post1
  - azureml-telemetry==1.57.0
  - scikit-learn==1.5.2
  - joblib==1.4.2
  - scipy==1.14.1
  - matplotlib==3.9.2
  # azureml-automl-common-tools packages
  - py-spy==0.3.12
  - debugpy~=1.6.3
  - ipykernel~=6.0
  - tensorboard
  - psutil~=5.8.0
  - tqdm~=4.66.3
  - py-cpuinfo==5.0.0
  - torch-tb-profiler~=0.4.0
  - mlflow-skinny==2.16.2
